### ISSUE TITLE
Website v1 content

### ISSUE THREAD

**Issue by Ankarrr** [ETHTaipei/ETH-Taipei-Website#3]
# Todo

- [x] Logo 確認
- [x] 文字內容確定：介紹、Hackathon、Conference
- [x] Social Links: TG, Discord, Twitter
- [x] Apply Links: for Speaker, Sponsor, Volunteer
- [ ] Speakers
  - 正在收集中 https://www.notion.so/eth-taipei/Invited-Speakers-8dff2db5ba364aca9a5d13590e3f3d21?pvs=4
- [x] Sponsors & Organizers: 因為現在 Sponsors 大多還在談，所以我想說先放在一起
   - Perpetual, Quantstamp, Lyra, imToken, Code4Rena, Diamond Protocol, Furucombo, Code4Rena, Taipei Ethereum Meetup
   - 需要按照字母順序排序
- [x] Partners: 
  - Unlock https://unlock-protocol.com/
  - Taikai https://taikai.network/

**Comment by Ankarrr** [comment]
歡迎來到 ETHTaipei，這是台灣舉辦的第一屆以 Ethereum 為主題的盛大活動。台灣擁有著非常活躍的 Ethereum 社群和開發者社群，因此 ETHTaipei 聚集了來自世界各地的 Ethereum 相關團隊，讓他們能夠更深入了解台灣這個重要的區塊鏈技術熱點，同時也讓台灣團隊有機會與世界接軌，被更多人認識。

在 ETHTaipei，您將有機會聆聽國內外知名專家、學者和業界領袖分享最前沿的 Ethereum 技術發展趨勢和應用案例，同時也能參與各種互動式工作坊、Hackathon 等活動，與來自各地的開發者交流並共同創造更多有價值的區塊鏈應用。

我們相信 ETHTaipei 將成為您認識台灣區塊鏈技術和開發者社群的絕佳機會，也希望能與您一同推動 Ethereum 技術在世界的發展，讓我們攜手共創更美好的未來。

Welcome to the first ETHTaipei held in Taiwan. With a very active Ethereum community and developer community in Taiwan, ETHTaipei has brought together Ethereum-related teams from around the world to gain a deeper understanding of Taiwan as an important hub for blockchain technology. At the same time, this event provides Taiwanese teams with the opportunity to connect with the world and gain more exposure.

At ETHTaipei, you will have the opportunity to listen to well-known experts, scholars, and industry leaders from around the world share the latest trends and application cases of Ethereum. You can also participate in hackathons, various workshops, and other activities to exchange ideas with developers from around the world and create more valuable blockchain applications together.

We believe that ETHTaipei will be an excellent opportunity for you to get to learn cutting-edge Ethereum technology and applications, and know the Ethereum community in Taiwan. We also hope to work with you to promote the development of Ethereum technology around the world and create a better future together.

**Comment by Ankarrr** [comment]
# Hackathon

The ETHTaipei hackathon is a three-day event where developers can compete for prizes sponsored by our sponsors. Participants will work together in teams to develop cutting-edge blockchain applications using Ethereum technologies. The hackathon is free to attend and includes workshops and talks from industry experts. It's the perfect opportunity to gain hands-on experience and connect with other blockchain enthusiasts from around the world.

**Comment by Ankarrr** [comment]
# Conference

The ETHTaipei conference is a two-day event featuring two tracks: **DeFi** and **Ethereum Technology**. The DeFi track focuses on decentralized finance, while the Ethereum Technology track covers a range of topics including Zero-Knowledge Proofs, Layer 2, Security, and more. This event brings together industry experts and innovators to explore the latest developments in blockchain technology. **Tickets** are required to attend and provide access to both tracks and networking opportunities.

**Comment by Ankarrr** [comment]
# Social Links 
- https://twitter.com/EthTaipei
- https://t.me/ethtaipei
- https://discord.gg/VqSyHjQYew

**Comment by Ankarrr** [comment]
# Apply Links

- Sponsors (Deck 連結)
- Speaker https://tally.so/r/wkb6V1
- Volunteers https://a25m38nlxgh.typeform.com/to/S0K3cTq9
