### ISSUE TITLE
Add Organizer, Community Supporter

### ISSUE THREAD

**Issue by Ankarrr** [ETHTaipei/ETH-Taipei-Website#49]
# Description

Martinet: 

> Sponsors 跟 Organizer 要分開，Organizer 用 https://docsend.com/view/5i6f3dn6uc2j69qn 第三頁這些個人，不要用組織。組織露出的方式可以開額外一個分類 Community Supporter
> 
> Community Supporter 包含：
> Diamond Protocol, Furucombo, imToken, Lyra, Perpetual Protocol, Quantstamp, Taipei Ethereum Meetup.
> 
> Sponsors 包含：
> Appworks, Autopass, Code4rena, Perpetual Protocol (有說要 donate, perks 還沒決定）, Quantstamp （有要付錢拿 Coffee Stand）, Selene, Tenderly, Term Structure

# Todo
- [ ] Add Organizers。名單和照片在 [贊助 deck](https://docs.google.com/presentation/d/1mvjg8huvnthxW3G6Iq24G5reYgEkpolJRif4f-reSv4/edit?usp=sharing) page 3
- [ ] Add Community Supporters，在 Partners 內。名單：Diamond Protocol, Furucombo, imToken, Lyra, Perpetual Protocol, Quantstamp, Taipei Ethereum Meetup.

順序為：
1. Sponsors
2. Partners
3. Organizers

# 問題
- [x] Community Supporters 納入 Partners 會不會比較好？OK 納入 partners
